---
title: "Cards experiment analysis"
output: html_notebook
---

```{r}
library(rjson)
library(tidyverse)
library(Hmisc)

```

```{r}
theme_set(theme_classic())
```

# load data

```{r data_loading}
data_dir = "../raw_data/ex0_1/"
data_files = list.files(data_dir)

cards_data = replicate(length(data_files), data.frame())

for (i in 1:length(data_files)) {
  f = data_files[i]
  this_subj_data_list = fromJSON(file=sprintf("%s/%s", data_dir, f))
  if (length(this_subj_data_list) == 6) {
    print(i)
    # flunked out
    next
  }
  this_subj_cards_data = data.frame()
  this_subj_global_data = data.frame()
  
  this_subj_card_data = this_subj_data_list[unlist(lapply(this_subj_data_list, function(x) {x$trial_type == "card_game"}))] %>%
    bind_rows()
  this_subj_attention_check_data = this_subj_data_list[unlist(lapply(this_subj_data_list, function(x) {x$trial_type == "survey-multi-choice" && x$response_trial_type == "attention_check"}))]
  
  att_chk_response = str_extract(this_subj_attention_check_data[[1]]$responses, '(?<=\\"Q0\\":\\")[A-za-z0-9. ]*(?=\\")')
  
  this_subj_card_data$attention_check_response = att_chk_response
  this_subj_card_data$subject_id = i
  cards_data[[i]] = this_subj_card_data
}
cards_data = bind_rows(cards_data)
```

# basic data processing

```{r}
cards_data = cards_data %>%
  mutate(experiment_phase = case_when(
    block == 1 ~ "training",
    block == 2 ~ "testing_basic",
    block == 3 ~ "testing_losing"
  ),
  attention_check_correct = attention_check_response == "Bet and my hand loses.",
  normalized_expected_earnings=expected_earnings/10,
  subject_id = as.factor(subject_id))
```


# Simple plots

```{r}
ggplot(cards_data %>% 
         filter(experiment_phase != "training"),
       aes(x = experiment_phase,
           y = normalized_expected_earnings,
           group = subject_id)) +
  geom_line(stat="summary",
            fun.y="mean",
            alpha=0.2) +
  geom_line(aes(group=1),
            stat="summary",
            fun.y="mean",
            color="red",
            size=2) +
  geom_hline(yintercept=0.25, linetype=2, alpha=0.5) +
  geom_hline(yintercept=0., linetype=3, alpha=0.5) +
  geom_hline(yintercept=-0.25, linetype=2, alpha=0.5) +
  facet_wrap(~ attention_check_correct) 

ggsave("plots/pilot2_results.png", width=7, height=4)
```

```{r}
ggplot(cards_data %>% 
         filter(experiment_phase != "training",
                attention_check_correct) %>%
         mutate(experiment_phase = ifelse(experiment_phase == "testing_basic", "Winning", "Losing")),
       aes(x = experiment_phase,
           y = normalized_expected_earnings * 4,
           color = "Human",
           group = subject_id)) +
  geom_line(stat="summary",
            fun.y="mean",
            color="#984ea3",
            alpha=0.2) +
  geom_line(aes(group=1),
            stat="summary",
            fun.y="mean",
            color="#984ea3",
            size=2) +
  geom_hline(yintercept=1, linetype=2, alpha=0.5) +
  geom_hline(yintercept=0., linetype=3, alpha=0.5) +
#  geom_hline(yintercept=-1, linetype=2, alpha=0.5) +
  labs(x="Experiment phase", y="Normalized expected earnings") +
  scale_y_continuous(breaks=c(0., 0.5, 1.)) +
  annotate("text", x=0.57, y=0.03, alpha=0.5, label="Chance") +
  annotate("text", x=0.57, y=0.97, alpha=0.5, label="Optimal") +
  guides(color=F)

#ggsave("../../dissertation/3-human-adaptation/figures/human_adaptation.png", width=6, height=4)
#ggsave("plots/mapping_results_passed.png", width=7, height=4)
```

```{r}
ggplot(cards_data %>% 
         filter(experiment_phase != "training",
                attention_check_correct) %>%
         mutate(experiment_phase = ifelse(experiment_phase == "testing_basic", "Basic evaluation", "Losing evaluation")),
       aes(x = experiment_phase,
           y = normalized_expected_earnings * 4,
           group = subject_id)) +
  geom_hline(yintercept=1, linetype=2, alpha=0.5) +
  geom_hline(yintercept=0., linetype=3, alpha=0.5) +
  geom_hline(yintercept=-1, linetype=2, alpha=0.5) +
  geom_line(stat="summary",
            fun.y="mean",
            color = "#984ea3",
            alpha=0.2) +
  geom_line(aes(group=1),
            stat="summary",
            fun.y="mean",
            color = "#984ea3",
            size=2) +
  scale_color_brewer(palette="Set1") +
  labs(x="Experiment phase", y="Normalized expected earnings") +
  annotate("text", x=0.57, y=0.05, alpha=0.5, label="Chance") +
  annotate("text", x=0.57, y=0.95, alpha=0.5, label="Optimal") +
  guides(color=F)

ggsave("../../dissertation/3-human-adaptation/figures/human_adaptation_supp_earnings.png", width=6, height=4)

ggplot(cards_data %>% 
         filter(experiment_phase != "training",
                attention_check_correct,
                expected_value != 0),
       aes(x = experiment_phase,
           y = (1 * (bet > 0) + -1 * (bet == 0)) * (1 * (expected_value > 0) + -1 * (expected_value < 0) ),
           group = subject_id)) +
  geom_hline(yintercept=0., linetype=2, alpha=0.5) +
  geom_hline(yintercept=0.5, linetype=3, alpha=0.5) +
  geom_hline(yintercept=1., linetype=2, alpha=0.5) +
  geom_line(stat="summary",
            fun.y="mean",
            color="#984ea3",
            alpha=0.2) +
  geom_line(aes(group=1),
            stat="summary",
            fun.y="mean",
            color="#984ea3",
            size=2) +
  scale_color_brewer(palette="Set1") +
  labs(x="Experiment phase", y="Accuracy (bet if value > 0)") +
  annotate("text", x=0.57, y=0.53, alpha=0.5, label="Chance") +
  annotate("text", x=0.57, y=0.97, alpha=0.5, label="Optimal") +
  guides(color=F)

ggsave("../../dissertation/3-human-adaptation/figures/human_adaptation_supp_accuracy.png", width=6, height=4)
#ggsave("plots/mapping_results_accuracy.png", width=6, height=4)
```

```{r}
ggplot(cards_data %>% 
         filter(experiment_phase != "training",
                attention_check_correct),
       aes(x = expected_value,
           y = 1*(bet > 0),
           group = subject_id)) +
  geom_point(stat="summary",
             fun.y="mean",
             position="jitter") +
  stat_smooth(geom="line", method="glm", method.args = list(family = "binomial"),
              se=F, alpha=0.3, size=1, color="black") +
  geom_smooth(aes(group=1), 
              method="glm",
              method.args = list(family = "binomial"),
              se=F,
              color="blue") +
  geom_vline(xintercept=0., color="red", linetype=2, size=2) +
  labs(x="Expected return", y="Fraction non-zero bets") +
  facet_wrap(~ experiment_phase)

ggsave("plots/subject_response_fits.png", width=7, height=4)
```

```{r}
ggplot(cards_data %>%
         filter(experiment_phase != "training"),
       aes(x=subject_id, fill=as.factor(bet*5))) +
  geom_bar(position="stack") +
  facet_wrap(~ experiment_phase) +
  scale_fill_brewer(palette="Dark2") +
  guides(fill=guide_legend(title="Bet"))
```


```{r}
ggplot(cards_data %>%
         filter(experiment_phase != "training"),
       aes(x=expected_value, color=as.factor(bet*5))) +
  geom_density(size=2, stat="density") +
  facet_wrap(~ experiment_phase) +
  scale_color_brewer(palette="Dark2") +
  guides(color=guide_legend(title="Bet"))

ggsave("plots/bets_by_expected_value.png", width=7, height=4)
```


```{r}
cards_data %>% 
  filter(experiment_phase != "training") %>%
  group_by(subject_id, experiment_phase, attention_check_correct) %>%
  summarise(mean_norm_expected_earnings = mean(normalized_expected_earnings),
            mean_expected_earnings = mean(expected_earnings))
```

# dissertation plots

```{r}
for (phase in c("testing_basic", "testing_losing")) {
  ggplot(cards_data %>% 
           filter(experiment_phase == phase,
                  attention_check_correct),
         aes(x = expected_value,
             y = 1*(bet > 0),
             group = subject_id)) +
    geom_point(stat="summary",
               fun.y="mean",
               position="jitter") +
    stat_smooth(geom="line", method="glm", method.args = list(family = "binomial"),
                se=F, alpha=0.3, size=1, color="black") +
    geom_smooth(aes(group=1), 
                method="glm",
                method.args = list(family = "binomial"),
                se=F,
                color="#377eb8",
                size=1.5) +
    geom_vline(xintercept=0., color="#e41a1c", linetype=2, size=1.5) +
    labs(x="Expected return", y="Fraction non-zero bets")
  
  ggsave(sprintf("../../dissertation/3-human-adaptation/figures/%s_subject_response_fits.png", phase), width=4, height=3)
  
  ggplot(cards_data %>%
         filter(experiment_phase == phase),
         aes(x=expected_value, color=as.factor(bet * 5))) +
    geom_density(size=2, stat="density") +
    scale_color_manual(values=c("#bfd3e6", "#8c6bb1", "#4d004b")) +
    guides(color=guide_legend(title="Bet")) +
    labs(x="Expected value of hand", y="Density of responses")
  
  ggsave(sprintf("../../dissertation/3-human-adaptation/figures/%s_bet_densities.png", phase), width=4, height=3)
}
```

## combined adaptation plot

```{r}
homm_data = read_csv("HoMM_data.csv") %>%
  mutate(experiment_phase = ifelse(task == "source", "Basic evaluation", "Losing evaluation"),
         result_type = gsub("Language baseline", "Language", result_type)) %>%
  select(-task) %>%
  rename(subject_id = run)  # model runs ~= subjects
```

```{r}
summarized_human_data = cards_data %>% 
  filter(experiment_phase != "training",
         attention_check_correct) %>%
  mutate(experiment_phase = ifelse(experiment_phase == "testing_basic", "Basic evaluation", "Losing evaluation"),
         expected_reward = expected_earnings / 5) %>%  # match bet scales
  select(subject_id, experiment_phase, expected_reward) %>%
  group_by(subject_id, experiment_phase) %>%
  summarise(expected_reward = mean(expected_reward)) %>%
  ungroup() %>%
  mutate(result_type = "Human",
         subject_id = as.numeric(subject_id))
```

```{r}
homm_and_human_data = bind_rows(homm_data, summarized_human_data) %>%
  mutate(expected_reward = expected_reward / 0.53,  # this makes optimal approx. 1.
         subject_id = case_when(result_type == "Human" ~ subject_id,
                                result_type == "HoMM" ~ subject_id + 40,
                                T ~ subject_id + 50),  # this just makes the plot work
         experiment_phase = factor(experiment_phase, 
                                   levels = c("Basic evaluation", "Losing evaluation"),
                                   labels = c("Winning", "Losing")))
```

```{r}
homm_lang_baseline_data = homm_and_human_data %>%
  filter(grepl("Language", result_type)) %>%
  mutate(result_type = factor(result_type))
```

```{r}
homm_and_human_data = homm_and_human_data %>%
  filter(result_type %in% c("Human", "HoMM", "Language")) %>%
  mutate(result_type = factor(result_type))
```

Some nominal data for demonstration purposes:
```{r}
ggplot(data.frame(result_type = factor(c(0, 0, 1, 1, 2, 2), labels=c("Perfect\nadaptation", "Getting\nconfused", "No\nadaptation")),
                  experiment_phase = factor(rep(c("Winning", "Losing"), times=3),
                                            levels=c("Winning", "Losing")),
                  expected_reward = c(1, 1, 1, 0., 1, -1)),
       aes(x = experiment_phase,
           y = expected_reward,
           color = result_type,
           group = result_type)) +
  geom_hline(yintercept=1, linetype=2, alpha=0.5) +
  geom_hline(yintercept=0., linetype=3, alpha=0.5) +
  geom_line(stat="identity", size=3) +
#  geom_hline(yintercept=-1, linetype=2, alpha=0.5) +
#  scale_color_brewer(palette="Set1") +
  scale_color_manual(values=c("#1a9850", "#888888", "#000000")) +
  labs(x="Experiment phase", y="Normalized expected earnings") +
  annotate("text", x=0.57, y=0.03, alpha=0.5, label="Chance") +
  annotate("text", x=0.57, y=0.97, alpha=0.5, label="Optimal") +
  coord_cartesian(ylim=c(-0.1, 1.05)) +
  guides(color=guide_legend(title=""))

ggsave("../../../assorted_talks/HoMM/figures/cards_patterns_interpretation.png", width=6, height=4)
```

```{r}
ggplot(homm_and_human_data %>%
         filter(result_type=="Human"),
       aes(x = experiment_phase,
           y = expected_reward,
           color = result_type)) +

  geom_hline(yintercept=1, linetype=2, alpha=0.5) +
  geom_hline(yintercept=0., linetype=3, alpha=0.5) +
  geom_line(aes(group=as.factor(subject_id)),
            alpha=0.5) +
  geom_line(aes(group=result_type),
            stat="summary",
            fun.y="mean",
            size=3) +
#  geom_hline(yintercept=-1, linetype=2, alpha=0.5) +
#  scale_color_brewer(palette="Set1") +
  scale_color_manual(values=c("#e41a1c", "#984ea3", "#477ec8"), 
                     drop=F) +
  labs(x="Experiment phase", y="Normalized expected earnings") +
  annotate("text", x=0.57, y=0.03, alpha=0.5, label="Chance") +
  annotate("text", x=0.57, y=0.97, alpha=0.5, label="Optimal") +
  scale_y_continuous(limits=c(-0.2, 1.02), breaks=c(0., 0.5, 1.)) +
  guides(color=F)  

ggsave("../../dissertation/3-human-adaptation/figures/human_adaptation.png", width=6, height=4)
```

```{r}
ggplot(homm_and_human_data,
       aes(x = experiment_phase,
           y = expected_reward,
           color = result_type)) +

  geom_hline(yintercept=1, linetype=2, alpha=0.5) +
  geom_hline(yintercept=0., linetype=3, alpha=0.5) +
  geom_line(aes(group=as.factor(subject_id)),
            alpha=0.5) +
  geom_line(aes(group=result_type),
            stat="summary",
            fun.y="mean",
            size=3) +
#  geom_hline(yintercept=-1, linetype=2, alpha=0.5) +
#  scale_color_brewer(palette="Set1") +
  scale_color_manual(values=c("#e41a1c", "#984ea3", "#477ec8")) +
  labs(x="Experiment phase", y="Normalized expected earnings") +
  annotate("text", x=0.57, y=0.03, alpha=0.5, label="Chance") +
  annotate("text", x=0.57, y=0.97, alpha=0.5, label="Optimal") +
  scale_y_continuous(limits=c(-0.2, 1.02), breaks=c(0., 0.5, 1.)) +
  guides(color=guide_legend(title=""))  +
  theme(legend.position=c(0.9, 0.4))

ggsave("../../dissertation/3-human-adaptation/figures/human_adaptation_vs_HoMM.png", width=6, height=4)
```

```{r}
ggplot(homm_and_human_data %>%
         filter(result_type != "Human"),
       aes(x = experiment_phase,
           y = expected_reward,
           color = result_type)) +
  geom_hline(yintercept=1, linetype=2, alpha=0.5) +
  geom_hline(yintercept=0., linetype=3, alpha=0.5) +
  geom_line(aes(group=result_type),
            stat="summary",
            fun.y="mean",
            size=2) +
  geom_line(aes(group=as.factor(subject_id)),
            alpha=0.5) +
#  geom_hline(yintercept=-1, linetype=2, alpha=0.5) +
#  scale_color_brewer(palette="Set1", drop=F) +
  scale_color_manual(values=c("#e41a1c", "#984ea3",  "#477ec8"), drop=F) +
  labs(x="Experiment phase", y="Normalized expected earnings") +
  annotate("text", x=0.57, y=0.03, alpha=0.5, label="Chance") +
  annotate("text", x=0.57, y=0.97, alpha=0.5, label="Optimal")+
  guides(color=guide_legend(title=""))

ggsave("../../dissertation/3-human-adaptation/figures/adaptation_HoMM_langauge.png", width=6, height=4)
```

```{r}
ggplot(homm_and_human_data %>%
         filter(result_type == "HoMM"),
       aes(x = experiment_phase,
           y = expected_reward,
           color = result_type)) +
  geom_hline(yintercept=1, linetype=2, alpha=0.5) +
  geom_hline(yintercept=0., linetype=3, alpha=0.5) +
  geom_line(aes(group=result_type),
            stat="summary",
            fun.y="mean",
            size=2) +
  geom_line(aes(group=as.factor(subject_id)),
            alpha=0.5) +
#  geom_hline(yintercept=-1, linetype=2, alpha=0.5) +
#  scale_color_brewer(palette="Set1", drop=F) +
  scale_color_manual(values=c("#e41a1c", "#984ea3",  "#477ec8"), drop=F) +
  labs(x="Experiment phase", y="Normalized expected earnings") +
  annotate("text", x=0.57, y=0.03, alpha=0.5, label="Chance") +
  annotate("text", x=0.57, y=0.97, alpha=0.5, label="Optimal")+
  guides(color=guide_legend(title=""))

ggsave("../../dissertation/3-human-adaptation/figures/adaptation_HoMM_only.png", width=6, height=4)
```
### MM paper plot and analysis
```{r}
ggplot(homm_and_human_data %>%
         mutate(experiment_phase = factor(experiment_phase, labels=c("Winning\n(trained)", "Losing\n(zero-shot adaptation)"))),
       aes(x = experiment_phase,
           y = expected_reward,
           color = result_type)) +

  geom_hline(yintercept=1, linetype=2, alpha=0.5) +
  geom_hline(yintercept=0., linetype=3, alpha=0.5) +
  geom_line(aes(group=as.factor(subject_id)),
            alpha=0.2) +
  geom_line(aes(group=result_type),
            stat="summary",
            fun.y="mean",
            size=1.5) +
#  geom_hline(yintercept=-1, linetype=2, alpha=0.5) +
#  scale_color_brewer(palette="Set1") +
  scale_color_manual(values=c("#e41a1c", "#984ea3", "#477ec8")) +
  scale_y_continuous(breaks=c(0., 0.5, 1.), labels=c("0%", "50%", "100%")) +
  scale_x_discrete(expand=c(0.2, 0.2)) +
  labs(x="Experiment phase", y="Normalized expected earnings") +
  annotate("text", x=2.2, y=0.05, alpha=0.5, label="Chance") +
  annotate("text", x=2.2, y=1.05, alpha=0.5, label="Optimal") +
  guides(color=guide_legend(title=NULL)) +
  theme(legend.position=c(0.15, 0.3),
        legend.key.size = unit(0.5, 'lines'))

ggsave("../../../networks/metamapping_paper/figures/cards_results.png", width=4, height=3)
```

```{r}
set.seed(0)
homm_and_human_data %>%
  mutate(experiment_phase = factor(experiment_phase, labels=c("Winning\n(trained)", "Losing\n(zero-shot adaptation)"))) %>%
  group_by(experiment_phase, result_type) %>%
  do(results=mean_cl_boot(.$expected_reward, na.rm=T)) %>%
  mutate(mean_expected_reward=results$y,
         CIlow=results$ymin,
         CIhigh=results$ymax)
```


## change plot + test

```{r}
change_data = homm_and_human_data %>%
  spread(experiment_phase, expected_reward) %>%
  mutate(ratio=Losing/Winning)
```

```{r}
t.test(ratio ~ result_type, change_data %>%
         filter(result_type != "Human"), paired=T)
t.test(ratio ~ result_type, change_data %>%
         filter(result_type != "Language"))
```
```{r}
perm_mean_diff_test = function(x, y, alpha=0.05) {
  obs_t = t.test(x, y)$statistic
  combined_data = c(x, y)
  n_combined = length(combined_data)
  n_x = length(x)
  perm_iterate = function(x, y) {
    perm = sample(n_combined)
    x_samp = combined_data[perm[1:n_x]]
    y_samp = combined_data[perm[-(1:n_x)]]
    this_t = t.test(x_samp, y_samp)$statistic
    return(this_t)
  }
  perms = replicate(500, perm_iterate(x, y))
  quants = quantile(perms, probs=c(alpha/2, 1-alpha/2))
  return(obs_t < quants[1] | obs_t > quants[2])
}
```

```{r}
set.seed(0)  # reproducibility
perm_mean_diff_test(change_data %>% 
                      filter(result_type == "HoMM") %>% 
                      pull(ratio),
                    change_data %>% 
                      filter(result_type == "Human") %>% 
                      pull(ratio))

perm_mean_diff_test(change_data %>% 
                      filter(result_type == "HoMM") %>% 
                      pull(ratio),
                    change_data %>% 
                      filter(result_type == "Language") %>% 
                      pull(ratio))

perm_mean_diff_test(change_data %>% 
                      filter(result_type == "HoMM") %>% 
                      pull(ratio),
                    change_data %>% 
                      filter(result_type == "Language") %>% 
                      pull(ratio),
                    0.005)
```

```{r}
ggplot(change_data,
       aes(x = result_type,
           y = ratio,
           color = result_type)) +

  geom_hline(yintercept=1, linetype=2, alpha=0.5) +
  geom_hline(yintercept=0., linetype=3, alpha=0.5) +
  geom_hline(yintercept=-1, linetype=2, alpha=0.5) +
  geom_errorbar(stat="summary",
                fun.data="mean_cl_normal",
                width=0.25,
                size=1) +
  geom_point(stat="summary",
             fun.y="mean",
             size=4) +
#  geom_hline(yintercept=-1, linetype=2, alpha=0.5) +
#  scale_color_brewer(palette="Set1") +
  scale_color_manual(values=c("#e41a1c", "#984ea3", "#477ec8")) +
  labs(x="Type", y="Losing expected earnings (% of winning)") +
  annotate("text", x=0.6, y=0.07, alpha=0.5, label="Chance") +
  annotate("text", x=0.84, y=1.07, alpha=0.5, label="Optimal adaptation") +
  annotate("text", x=0.74, y=-0.93, alpha=0.5, label="No adaptation") +
  annotate("path",x=c(1,1,2,2),y=c(1.4,1.5,1.5,1.4),alpha=0.5) +
  annotate("text", x=1.5, y=1.57, alpha=0.5, label="n.s. (both p > 0.05)") +
  annotate("path",x=c(1,1,3,3),y=c(1.55,1.65,1.65,1.55),alpha=0.5) +
  annotate("text", x=2, y=1.73, alpha=0.5, label="p < 0.01 (both perm- and t-test)") +
  scale_y_continuous(breaks = c(-1, 0, 1), labels = c("-100%", "0%", "100%")) +
  guides(color=F)

ggsave("../../dissertation/3-human-adaptation/figures/change_scores.png", width=6, height=4)
```


# Are humans improving during the testing phase?

```{r}
less_summarized_human_data = cards_data %>% 
  filter(experiment_phase != "training",
         attention_check_correct) %>%
  mutate(experiment_phase = ifelse(experiment_phase == "testing_basic", "Basic evaluation", "Losing evaluation"),
         expected_reward = expected_earnings / 5, # match bet scales
         phase_half = case_when(trial_index <= 52 ~ 1,
                                trial_index <= 64 ~ 2,
                                trial_index <= 81 ~ 3,
                                T ~ 4)) %>%  
  select(subject_id, experiment_phase, expected_reward, phase_half) %>%
  group_by(subject_id, experiment_phase, phase_half) %>%
  summarise(expected_reward = mean(expected_reward)) %>%
  ungroup() %>%
  mutate(result_type = "Human",
         subject_id = as.numeric(subject_id)) %>%
  mutate(expected_reward = expected_reward / 0.53,  # this makes optimal approx. 1.
         experiment_phase = factor(experiment_phase, 
                                   levels = c("Basic evaluation", "Losing evaluation"),
                                   labels = c("Winning", "Losing")))
```


```{r}
ggplot(less_summarized_human_data,
       aes(x = phase_half,
           y = expected_reward)) +

  geom_hline(yintercept=1, linetype=2, alpha=0.5) +
  geom_hline(yintercept=0., linetype=3, alpha=0.5) +
  geom_line(aes(group=as.factor(subject_id)),
            alpha=0.2) +
  geom_line(aes(group=result_type),
            stat="summary",
            fun.y="mean",
            size=1.5) +
#  geom_hline(yintercept=-1, linetype=2, alpha=0.5) +
#  scale_color_brewer(palette="Set1") +
  scale_color_manual(values=c("#e41a1c", "#984ea3", "#477ec8")) +
  scale_y_continuous(breaks=c(0., 0.5, 1.), labels=c("0%", "50%", "100%")) +
  labs(x="Experiment phase", y="Normalized expected earnings") +
  annotate("text", x=2.2, y=0.05, alpha=0.5, label="Chance") +
  annotate("text", x=2.2, y=1.05, alpha=0.5, label="Optimal") +
  guides(color=guide_legend(title=NULL)) +
  theme(legend.position=c(0.15, 0.3),
        legend.key.size = unit(0.5, 'lines'))

ggsave("plots/little_learning_within_testing.png")
```


# is a task-conditioned (not hyper) architecture better for language generalization?

```{r}
ggplot(homm_lang_baseline_data,
       aes(x = experiment_phase,
           y = expected_reward,
           color = result_type)) +
  geom_hline(yintercept=1, linetype=2, alpha=0.5) +
  geom_hline(yintercept=0., linetype=3, alpha=0.5) +
  geom_line(aes(group=interaction(as.factor(subject_id), result_type)),
            alpha=0.5) +
  geom_line(aes(group=result_type),
            stat="summary",
            fun.y="mean",
            size=3) +
#  geom_hline(yintercept=-1, linetype=2, alpha=0.5) +
#  scale_color_brewer(palette="Set1") +
  scale_color_manual(values=c("#477ec8", "#08519c"),
                     labels=c("Language\n(HyperNetwork)",
                              "Language\n(Task-concatenated)")) +
  labs(x="Experiment phase", y="Normalized expected earnings") +
  annotate("text", x=0.57, y=0.03, alpha=0.5, label="Chance") +
  annotate("text", x=0.57, y=0.97, alpha=0.5, label="Optimal") +
  scale_y_continuous(limits=c(-0.2, 1.02), breaks=c(0., 0.5, 1.)) +
  guides(color=guide_legend(title=""))  +
  theme(legend.position=c(0.9, 0.4))

ggsave("../../dissertation/3-human-adaptation/figures/cards_lang_hyper_vs_tcnh.png", width=6, height=4)
ggsave("../../../networks/metamapping_paper/figures/cards_lang_hyper_vs_tcnh.png", width=4, height=3)
```